[package]
name = "lithiumd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "lithiumd"
path = "src/main.rs"

[dependencies]
udev = "0.7"
mio = { version = "0.8", features = ["os-ext"] }
